### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alexvcasillas** [alexvcasillas/animated-styled-components#3]
A nice clean and easy to understand documentation must be created.

**Comment by oyeanuj** [comment]
@alexvcasillas In addition, having a demo to quickly demo the features would be super helpful as well! Thanks for putting out this library!

**Comment by alexvcasillas** [comment]
Hi @oyeanuj ! Thanks for the feedback !
There's a demo in CodeSandbox but it's not working at the moment because an issue we're trying to find in CodeSandbox. But I will put an online demo shortly : )

Link to CodeSandbox: [https://codesandbox.io/s/x7nxpw700z](https://codesandbox.io/s/x7nxpw700z)
