### ISSUE TITLE
Cannot use 'in' operator to search for 'type' in undefined

### ISSUE THREAD

**Issue by bplittle** [alexvcasillas/animated-styled-components#30]
`animated.js:1 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'type' in undefined`
`if(!("type"in n))throw new TypeError("You're missing the type of transition property. Eg: hover, focus, blur, active, ...");`
```
<Animated>
              <div/>
            </Animated>
```

**Comment by alexvcasillas** [comment]
Could you provide a working sandbox of this issue? :)

**Comment by alexvcasillas** [comment]
Thanks for reporting this issue @bplittle ! All the corrections have been implemented and merged with #31 and are now in master branch and ready to be used as the new 0.6.0 version.

Thanks for giving a try to Animated Styled Components and for reporting this bug :)
